import type { MealItem } from './types';

export const mealItems: MealItem[] = [
  // مشروبات روحية - Alcoholic Beverages (حسب الطلب)
{
  id: 900,
  name: 'عرق',
  category: 'مشروبات روحية',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'alcoholic beverage',
  description: 'مشروب كحولي حسب الطلب. لا يشمل ويسكي.',
},
{
  id: 901,
  name: 'بيرة (חבית)',
  category: 'مشروبات روحية',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'alcoholic beverage',
  description: 'مشروب كحولي حسب الطلب. لا يشمل ويسكي.',
},
{
  id: 902,
  name: 'نبيذ أبيض\\أحمر',
  category: 'مشروبات روحية',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'alcoholic beverage',
  description: 'مشروب كحولي حسب الطلب. لا يشمل ويسكي.',
},

  // مشروبات ساخنة - Hot Beverages
{
  id: 800,
  name: 'شاي',
  category: 'مشروبات ساخنة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'hot beverage',
  description: 'مشروب من قائمة مشروبات ساخنة.',
},
{
  id: 801,
  name: 'قهوة',
  category: 'مشروبات ساخنة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'hot beverage',
  description: 'مشروب من قائمة مشروبات ساخنة.',
},

  // مشروبات خفيفة - Light Beverages
{
  id: 700,
  name: 'كولا ومشتقاتها',
  category: 'مشروبات خفيفة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'light beverage',
  description: 'مشروب من قائمة مشروبات خفيفة.',
},
{
  id: 701,
  name: 'ماء',
  category: 'مشروبات خفيفة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'light beverage',
  description: 'مشروب من قائمة مشروبات خفيفة.',
},
{
  id: 702,
  name: 'عصير',
  category: 'مشروبات خفيفة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'light beverage',
  description: 'مشروب من قائمة مشروبات خفيفة.',
},
{
  id: 703,
  name: 'ليمون\\برتقال',
  category: 'مشروبات خفيفة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'light beverage',
  description: 'مشروب من قائمة مشروبات خفيفة.',
},
  // وجبات خاصة أكسترا - Extra Special Meals
{
  id: 600,
  name: 'موزة خروف مشوية بالفرن',
  category: 'وجبات خاصة أكسترا',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'extra special meal',
  description: 'طبق من قائمة وجبات خاصة أكسترا.',
},
{
  id: 601,
  name: 'رولادة خروف محشية بلحم وفستق حلي',
  category: 'وجبات خاصة أكسترا',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'extra special meal',
  description: 'طبق من قائمة وجبات خاصة أكسترا.',
},
{
  id: 602,
  name: 'ستيك انتريكوت مشوي',
  category: 'وجبات خاصة أكسترا',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'extra special meal',
  description: 'طبق من قائمة وجبات خاصة أكسترا.',
},
{
  id: 603,
  name: 'ضلع عبور وتيبون عبور مشوي',
  category: 'وجبات خاصة أكسترا',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'extra special meal',
  description: 'طبق من قائمة وجبات خاصة أكسترا.',
},
{
  id: 604,
  name: 'فيليه عجل مع ضلع عبور وكبدة وز',
  category: 'وجبات خاصة أكسترا',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'extra special meal',
  description: 'طبق من قائمة وجبات خاصة أكسترا.',
},
{
  id: 605,
  name: 'سمك فيليه\\ستيك دجاج',
  category: 'وجبات خاصة أكسترا',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'extra special meal',
  description: 'طبق من قائمة وجبات خاصة أكسترا.',
},
{
  id: 606,
  name: '2 سيخ لحمة',
  category: 'وجبات خاصة أكسترا',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'extra special meal',
  description: 'طبق من قائمة وجبات خاصة أكسترا.',
},
{
  id: 607,
  name: 'سيخ لحمة + سيخ كباب',
  category: 'وجبات خاصة أكسترا',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'extra special meal',
  description: 'طبق من قائمة وجبات خاصة أكسترا.',
},
{
  id: 608,
  name: 'ضلع خروف + صدر دجاج',
  category: 'وجبات خاصة أكسترا',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'extra special meal',
  description: 'طبق من قائمة وجبات خاصة أكسترا.',
},
  // وجبات أوّلية خاصة - Special Initial Meals
{
  id: 500,
  name: 'سيخ لحمة مشوي',
  category: 'وجبات أوّلية خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special initial meal',
  description: 'طبق من قائمة وجبات أوّلية خاصة.',
},
{
  id: 501,
  name: 'تيبون عبور مشوي',
  category: 'وجبات أوّلية خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special initial meal',
  description: 'طبق من قائمة وجبات أوّلية خاصة.',
},
{
  id: 502,
  name: 'شاورما عجل مقدمة مع لفه طابون',
  category: 'وجبات أوّلية خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special initial meal',
  description: 'طبق من قائمة وجبات أوّلية خاصة.',
},
{
  id: 503,
  name: 'قريدس كلماري مطبوخ مع صوص',
  category: 'وجبات أوّلية خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special initial meal',
  description: 'طبق من قائمة وجبات أوّلية خاصة.',
},
{
  id: 504,
  name: 'قريدس كلماري مقلي مع صوص',
  category: 'وجبات أوّلية خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special initial meal',
  description: 'طبق من قائمة وجبات أوّلية خاصة.',
},
{
  id: 505,
  name: 'سيخ قريدس مشوي',
  category: 'وجبات أوّلية خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special initial meal',
  description: 'طبق من قائمة وجبات أوّلية خاصة.',
},
{
  id: 506,
  name: 'فيليه سالمون مشوي بالفرن',
  category: 'وجبات أوّلية خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special initial meal',
  description: 'طبق من قائمة وجبات أوّلية خاصة.',
},
{
  id: 507,
  name: 'رقبه عبور محشي. فريكة\\ارز',
  category: 'وجبات أوّلية خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special initial meal',
  description: 'طبق من قائمة وجبات أوّلية خاصة.',
},
{
  id: 508,
  name: 'قص عبور محشي. فريكة\\ارز',
  category: 'وجبات أوّلية خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special initial meal',
  description: 'طبق من قائمة وجبات أوّلية خاصة.',
},
{
  id: 509,
  name: 'اسادو عجل مشوي بالفرن',
  category: 'وجبات أوّلية خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special initial meal',
  description: 'طبق من قائمة وجبات أوّلية خاصة.',
},
// وجبات أوّليّة - Initial Meals
{
  id: 400,
  name: 'سيخ برجيـت مشوي',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 401,
  name: 'جاط عرايس الشيف',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 402,
  name: 'صفيحة تركية مع لحمة\\دجاج\\جبنة\\سبانخ',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 403,
  name: 'منقط عجل مع الخضار',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 404,
  name: 'شينيتسيليونيم دجاج طازة',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 405,
  name: 'كوردون بلو مشوي\\مقلي',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 406,
  name: 'سيخ جبنة حلومي مشوي',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 407,
  name: 'فيليه سمك مطلي ومقلي',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 408,
  name: 'فطر محشي أجبان مشوي بالفرن\\مقلي',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 409,
  name: 'فطر موكرام مع صوص البشاميل',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 410,
  name: 'مربع جبنة مطلي ومقلي',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 411,
  name: 'سيخ كباب مشوي',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},
{
  id: 412,
  name: 'جاط كباب تركي مشوي مع الباذنجان',
  category: 'وجبات أوّليّة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'initial meal',
  description: 'طبق من قائمة وجبات أوّليّة.',
},

    // سلطات خاصة - Special Salads
{
  id: 300,
  name: 'باذنجان كامل مقدم مع طحينة بندورة وثوم كونفي',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 301,
  name: 'باذنجان مع البصل المكبوس وصلصة الفلفل الأخضر',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 302,
  name: 'سلطة فريكة مع لبنة مقلية',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 303,
  name: 'سلطة فطر طبيعي ساخن منقط مع خضار',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 304,
  name: 'سلطة بيبي سبانخ مع الفواكه',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 305,
  name: 'سلطة أرضي شوكي مشوي مع الحب وجبنة فته',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 306,
  name: 'سلطة جبنة حلومي',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 307,
  name: 'سلطة شاورما الدجاج',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 308,
  name: 'كبة تركية نية مع دبس الرمان',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 309,
  name: 'سيجار محشي لبنة زعتر أخضر، زيتون، بندورة ناشفة',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 310,
  name: 'كرنشي نيلة',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 311,
  name: 'سنيتشر زعتر',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 312,
  name: 'سلطة شيري ألوان مع جبنة الموتزاريلّا',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 313,
  name: 'جاط خضار لوز وجبنة',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
{
  id: 314,
  name: 'جاط أجبان خاصة',
  category: 'سلطات خاصة',
  price: 0,
  image: 'https://placehold.co/600x400.png',
  dataAiHint: 'special salad',
  description: 'سلطة من قائمة سلطات خاصة.',
},
  {
    id: 200,
    name: 'حمص يقدم مع حمص حب/صنوبر',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 201,
    name: 'تبولة',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 202,
    name: 'فتوش',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 203,
    name: 'يوناني',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 204,
    name: 'سلطة الريحان',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 205,
    name: 'سلطة بندورة شيري حراقة/حبق وجوز',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 206,
    name: 'سلطة ذرة',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 207,
    name: 'متبل باذنجان مقلي مع طحينة حمراء',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 208,
    name: 'متبل باذنجان مع الخضار',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 209,
    name: 'متبل باذنجان مع طحينة',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 210,
    name: 'متبل بيستو',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 211,
    name: 'متبل كوسا مع لبن وطحينة',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 212,
    name: 'لبنة متومة مقدمة مع صلصة، وخبز مقلي',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 213,
    name: 'طحينة، سماق، بندورة، بقدونس',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 214,
    name: 'سلطة تركية',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 215,
    name: 'سلطة جزر حراقة مطبوخة/أنيه',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 216,
    name: 'سلطة جزر حلوة',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 217,
    name: 'سلطة فطاريش طبيعي بارد',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 218,
    name: 'سلطة توتة مع خضار ومايونيز',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 219,
    name: 'سلطة زهرة مع طحينة/خضار',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 220,
    name: 'زهرة مقلية ومقلية مقدمة مع صوص الثوم',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 221,
    name: 'سلطة مكسرات مع الأعشاب',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 222,
    name: 'سلطة فتوش تركي مع الباذنجان',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 223,
    name: 'سلطة كينوا مع الأعشاب',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 224,
    name: 'سلطة بندورة مقشرة حارة',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 225,
    name: 'سلطة خضار مشوية',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 226,
    name: 'سلطة جرجير',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 227,
    name: 'سلطة جرجير مع الرمان، الشمندر وجبنة فته',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
  {
    id: 228,
    name: 'سلطة باذنجان مكدوس مع البرغل',
    category: 'سلطات السلطان',
    price: 0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salad item',
    description: 'سلطة من قائمة سلطات السلطان.',
  },
];

export const categories = [...new Set(mealItems.map((item) => item.category))];
