import type { MealItem } from './types';

export const mealItems: MealItem[] = [
  {
    id: 1,
    name: 'Caprese Skewers',
    category: 'Appetizers',
    price: 3.5,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'caprese skewers',
    description: 'Cherry tomatoes, mozzarella, basil, balsamic glaze.',
  },
  {
    id: 2,
    name: 'Bruschetta',
    category: 'Appetizers',
    price: 4.0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'bruschetta platter',
    description: 'Toasted baguette with tomato, garlic, and herbs.',
  },
  {
    id: 3,
    name: 'Mini Quiches',
    category: 'Appetizers',
    price: 4.5,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'mini quiches',
    description: 'Assortment of spinach, lorraine, and mushroom.',
  },
  {
    id: 4,
    name: 'Grilled Chicken',
    category: 'Main Courses',
    price: 25.0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'grilled chicken',
    description: 'Herb-marinated chicken breast with roasted vegetables.',
  },
  {
    id: 5,
    name: 'Salmon Fillet',
    category: 'Main Courses',
    price: 30.0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'salmon fillet',
    description: 'Pan-seared salmon with a lemon-dill sauce.',
  },
  {
    id: 6,
    name: 'Beef Tenderloin',
    category: 'Main Courses',
    price: 45.0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'beef tenderloin',
    description: 'Roasted beef tenderloin with a red wine reduction.',
  },
  {
    id: 7,
    name: 'Vegetable Lasagna',
    category: 'Main Courses',
    price: 22.0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'vegetable lasagna',
    description: 'Layers of pasta, cheese, and fresh vegetables.',
  },
  {
    id: 8,
    name: 'Chocolate Lava Cake',
    category: 'Desserts',
    price: 8.0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'lava cake',
    description: 'Warm chocolate cake with a molten center.',
  },
  {
    id: 9,
    name: 'New York Cheesecake',
    category: 'Desserts',
    price: 7.5,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'cheesecake slice',
    description: 'Classic cheesecake with a graham cracker crust.',
  },
  {
    id: 10,
    name: 'Fruit Tart',
    category: 'Desserts',
    price: 7.0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'fruit tart',
    description: 'A beautiful assortment of fresh seasonal fruits.',
  },
  {
    id: 11,
    name: 'Soft Drinks',
    category: 'Beverages',
    price: 2.5,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'soft drinks',
    description: 'Coke, Diet Coke, Sprite, Ginger Ale.',
  },
  {
    id: 12,
    name: 'Fresh Juice',
    category: 'Beverages',
    price: 4.0,
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'fresh juice',
    description: 'Orange, Apple, Cranberry.',
  },
];

export const categories = [...new Set(mealItems.map((item) => item.category))];
